### ISSUE TITLE
linkedin-client.com сейчас продается

### ISSUE THREAD

**Issue by iamsalnikov** [zoonman/linkedin-api-php-client#1]
В исходниках либы есть ссылка на linkedin-client.com, который доступен для покупки. Не успел еще обзавестись им, или это какой-то местный проблем?

![image](https://user-images.githubusercontent.com/3082586/29700995-95712662-8971-11e7-83ba-e62a493d4814.png)

**Comment by iamsalnikov** [comment]
Также в некоторых файлах есть ссылка, переход по которой ведет на 404:

![image](https://user-images.githubusercontent.com/3082586/29701226-1ce6cf74-8973-11e7-9670-709c156e4baf.png)

**Comment by zoonman** [comment]
Спасибо Леша! Исправим!
