### ISSUE TITLE
Fatal error: getBody() on null

### ISSUE THREAD

**Issue by reinhacker** [zoonman/linkedin-api-php-client#14]
Hi there,
following the given example, I get the following error, running only the following part of the example:

`  $profile = $client->get('people/~:(id,email-address,first-name,last-name)');
   pp($profile); // print profile information`

The error occurs after a user confirms access to LinkedIn within the LinkedIn confirmation screen.

>  Fatal error: Call to a member function getBody() on null in C:\Xampp\htdocs\LinkedInAnalyzer\vendor\zoonman\linkedin-api-php-client\src\Client.php on line 313

**Comment by zoonman** [comment]
Do you have tokens and keys in place?
I just ran it locally and it did work.

**Comment by zoonman** [comment]
@reinhacker could you provide code sample?

**Comment by reinhacker** [comment]
Sure, here's the code. Everything was installed using composer. Just replaced the environment files with client id / secret and removed the post requests:

`include_once 'vendor/autoload.php';
            
            // import client class
            use LinkedIn\Client;
            use LinkedIn\Scope;
            
            session_start();
            // instantiate the Linkedin client
            // you can setup keys using
            $client = new Client(
                '77o3rk7lf0jXXX', 'mZ4TKR5dzAh8MXXX'
            );
            
            if (isset($_GET['code'])) { // we are returning back from LinkedIn with the code
                if (isset($_GET['state']) &&  // and state parameter in place
                    isset($_SESSION['state']) && // and we have have stored state
                    $_GET['state'] === $_SESSION['state'] // and it is our request
                ) {
                    try {
                        // you have to set initially used redirect url to be able
                        // to retrieve access token
                        $client->setRedirectUrl($_SESSION['redirect_url']);
                        // retrieve access token using code provided by LinkedIn
                        $accessToken = $client->getAccessToken($_GET['code']);
                        echo 'Access token:';
                        pp($accessToken); // print the access token content
                        echo 'Profile:';
                        // perform api call to get profile information
                        $profile = $client->get(
                            'people/~:(id,email-address,first-name,last-name)'
                        );
                        pp($profile); // print profile information
                    } catch (\LinkedIn\Exception $exception) {
                        // in case of failure, provide with details
                        pp($exception);
                        pp($_SESSION);
                    }
                    echo '<a href="/">Start over</a>';
                } else {
                    // normally this shouldn't happen unless someone sits in the middle
                    // and trying to override your state
                    // or you are trying to change saved state during linking
                    echo 'Invalid state!';
                    pp($_GET);
                    pp($_SESSION);
                    echo '<a href="/">Start over</a>';
                }
            } elseif (isset($_GET['error'])) {
                // if you cancel during linking
                // you will be redirected back with reason
                pp($_GET);
                echo '<a href="/">Start over</a>';
            } else {
                // define desired list of scopes
                $scopes = Scope::getValues();
                $loginUrl = $client->getLoginUrl($scopes); // get url on LinkedIn to start linking
                $_SESSION['state'] = $client->getState(); // save state for future validation
                $_SESSION['redirect_url'] = $client->getRedirectUrl(); // save redirect url for future validation
                echo 'LoginUrl: <a href="'.$loginUrl.'">' . $loginUrl. '</a>';
            }
            /**
             * Pretty print whatever passed in
             *
             * @param mixed $anything
             */
            function pp($anything)
            {
                echo '<pre>' . print_r($anything, true) . '</pre>';
            }`

**Comment by reinhacker** [comment]
Alright, I could fix the problem for myself. It was not an issue with the code, but with a missing ssl certificate setup within my php.ini which leads to an invalid request and therefore leads to $response being null ;-)

**Comment by zoonman** [comment]
It is all right. Wrong PHP configuration led to the issue. Closing the ticket.
