### ISSUE TITLE
getAccessToken invalid request

### ISSUE THREAD

**Issue by jramirezgranada** [zoonman/linkedin-api-php-client#15]
Hi, 

So I've been testing your library but I need to work with linkedin v2, to get access token in v2 you would need to change the request in the getAccessToken, according to the linkedin documentation this url https://www.linkedin.com/oauth/v2/accessToken allow only post request method.

Have you thought to change that request method or validate the api version that developer is using ?

Thanks.

**Comment by zoonman** [comment]
Thank you!. I will check on it this night.

**Comment by zoonman** [comment]
Fixed in version #0.0.11.
