### ISSUE TITLE
Validation on filename while upload

### ISSUE THREAD

**Issue by sarhugo** [zoonman/linkedin-api-php-client#19]
Doing an image upload with file name: "Screenshot 2018-03-22 18.13.51.png" I received the following error from linkedin:

`Invalid file name: Screenshot 2018-03-22 18.13.51.png (Code: 400)`

Trying with different names I discovered that the problem was the dots in file name. Uploading as "Screenshot 2018-03-22 18-13-51.png" it worked fine.

Maybe SDK should preprocess the filename before sending it at upload method? I can make a PR with the logic

**Comment by zoonman** [comment]
I think you have to open a bug report with LinkedIn API team. 
The dots in the filename are totally legitimate symbols in all modern OS and filesystems. 
To the extent of my knowledge, file upload is the part of LinkedIn partner program for which you actually have to pay money. If you pay them they **must provide a support**.

**Comment by sarhugo** [comment]
Hi @zoonman, actually upload api is part of v2, which is free. It's access is granted by applying to their partner program but I haven't pay for it.

I agree with you that it's an API bug, but there isn't any way to report a bug to them. The only official support channel is stackoverflow (but I never get a reply from them)

I'll keep my fork to have it working for my clients

**Comment by zoonman** [comment]
I tried to get access to their Partner program but didn't succeed even we are enterprise grade company with hundreds employees.

**Comment by sarhugo** [comment]
It took about 1 month to get reply from them when applying ¯\_(ツ)_/¯

**Comment by zoonman** [comment]
I used to apply a year ago, nobody gets back to me.
