### ISSUE TITLE
How to get Company Profile fields

### ISSUE THREAD

**Issue by mafadotaiu** [zoonman/linkedin-api-php-client#21]
# What? Where? When?

When you are going to report a new issue, include the following information

1. Environment
2. Steps to reproduce

**Comment by zoonman** [comment]
I'd recommend to get yourself familiar with the documentation here https://developer.linkedin.com/docs/company-pages#company_profile

It should look like this:
```
$companyProfile = $client->get(
    'companies/123:(id,name,description)'
);
```
Where `123` is your company.
