### ISSUE TITLE
BUG syntax error

### ISSUE THREAD

**Issue by RomeoDavide91** [zoonman/linkedin-api-php-client#22]
# What? Where? When?

in php file in this row:
$linkedIn=new LinkedIn\Client($oauthToken,$oauthSecret);

response with status 500

<b>Parse error</b>:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in <b>/vendor/zoonman/linkedin-api-php-client/src/Client.php</b> on line <b>22</b><br />

cause of error:
<b>use function</b> GuzzleHttp\Psr7\build_query;

How do I solve?

**Comment by RomeoDavide91** [comment]
@zoonman What is the estimated time to fix the bug?

**Comment by zoonman** [comment]
I'll look into it this night.

**Comment by zoonman** [comment]
This not a bug, please, upgrade to PHP v5.6. You are using deprecated PHP version.

**Comment by RomeoDavide91** [comment]
But, I already have a latest version of PHP

**Comment by zoonman** [comment]
@RomeoDavide91, which is your PHP version?

**Comment by zoonman** [comment]
I assume you are using PHP 5.5. 
This library is going through automated tests with PHP 5.6 and PHP 7.0, hhvm and nightly PHP builds.

**Comment by RomeoDavide91** [comment]
I have this version: 
PHP 7.2.4-1+ubuntu14.04.1

Not a compatible version?

**Comment by zoonman** [comment]
This is very interesting, it did pass tests here https://travis-ci.org/zoonman/linkedin-api-php-client/jobs/377754536#L437 

Are you sure it is using PHP 7.2.4?
Try to add the following line and check results:
```
echo 'Current PHP version: ' . phpversion();
```
This is 100% legit code for PHP 7.2.4.
