### ISSUE TITLE
Bug syntax error

### ISSUE THREAD

**Issue by augustinejenin** [zoonman/linkedin-api-php-client#23]
It was working in php 7.
When tried to impliemnt this in php 5.6 I got an error "syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in vendor/zoonman/linkedin-api-php-client/src/Client.php on line 22"
line number 22 is this "use function GuzzleHttp\Psr7\build_query"

**Comment by zoonman** [comment]
Duplicate of #22

**Comment by zoonman** [comment]
This not a bug, please, upgrade to PHP v5.6. You are using deprecated PHP version.
