### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by rwilliam** [zoonman/linkedin-api-php-client#24]
I have try to installed using composer on php 7  and it's give me error .Please check below message 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package zoonman/linkedin-api-php-client No version set (parsed as 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

![lphp](https://user-images.githubusercontent.com/20833929/41146931-9daf8af6-6b22-11e8-87ec-2813989a5812.png)

**Comment by zoonman** [comment]
This is how it looks for me:

<img width="608" alt="screen shot 2018-06-18 at 15 35 59" src="https://user-images.githubusercontent.com/576297/41557987-6c6cb782-730d-11e8-9c68-30c7bb7fa345.png">

Which composer version are you using?
