### ISSUE TITLE
Post video

### ISSUE THREAD

**Issue by jeromepissis** [zoonman/linkedin-api-php-client#25]
Hi,

Thanks for you code. 
How can I use it if I want to post a video ? (For picture and text it's work)

Many thanks for your help.

**Comment by zoonman** [comment]
Hi!
Try to share a link to Youtube video, it should work. 
Also, you can try to upload your video to some storage like S3 and provide a direct link to the file. 
File should be in web-optimized mp4 format (you will need to [move moov atom](https://ffmpeg.org/ffmpeg-formats.html#mov_002c-mp4_002c-ismv)).

**Comment by KrishnaVishwakarma1595** [comment]
Hi,

I am also trying to post a video but it doesn't work, neither for youtube video nor for my video if I upload any. Can you please explain how can I post it using the above method that you have told. Is there any other endpoint or attribute to post a video.

Many thanks for your help.
