### ISSUE TITLE
How to get public profile of someone else?

### ISSUE THREAD

**Issue by kadnan** [zoonman/linkedin-api-php-client#26]
LinkedIn provide [option](https://developer.linkedin.com/docs/guide/v2/people/profile-api#public-profile-url) to access someone else profile details. How can I use the library to perform this operation as given here `https://api.linkedin.com/v2/people/(id:{person ID})`

**Comment by zoonman** [comment]
Adnan, you have to switch to v2 and provide custom headers:

```php
// init goes here...

// set X-RestLi-Protocol-Version:2.0.0 required to make API v2 work
$client->setApiHeaders([
  'Content-Type' => 'application/json',
  'x-li-format' => 'json',
  'X-Restli-Protocol-Version' => '2.0.0', // use protocol v2
  'x-li-src' => 'msdk' // set a src header to "msdk" to mimic a mobile SDK
]);

// tell Client to use API v2
$client->setApiRoot('https://api.linkedin.com/v2/');

// now you can get someone's else profile if you have access
// don't forget to replace {person ID} with actual value
$profile = $client->get(
    'people/(id:{person ID})'
);
print_r($profile);
```
Make sure your application has access to this portion of API.

**Comment by zoonman** [comment]
@kadnan any luck?

**Comment by kadnan** [comment]
@zoonman I did not try as the required api was not free

**Comment by zoonman** [comment]
Gotcha. Closing this issue.
