### ISSUE TITLE
How to get Refresh Token?

### ISSUE THREAD

**Issue by gkarthikeyanmca** [zoonman/linkedin-api-php-client#28]
Hello Zoonman,

Is there anyway we can have functions for following?

1. Get refresh token (https://developer.linkedin.com/docs/Refresh-Tokens-with-OAuth-2)
2. Exchange refresh token for a new access token, if access token is expired.

I am facing token expired error. Need to find a solution to fix this automatically.

Also i see there is no mention of refresh tokens anywhere in the SDK, if you can guide me through this, it will be a great help.

Many thanks,
Karthikeyan

**Comment by zoonman** [comment]
Hi Karthikeyan,
So far there is no support of refresh tokens in the current implementation.
Unfortunately I don't have partner's access therefore I am unable to test this function. Per documentation it is available only for LinkedIn partners.
I can implement support of refresh token blindly and I need someone with partner access level to help testing this functionality.

**Comment by gkarthikeyanmca** [comment]
I understand. Thanks for your time 👍 

Closing ticket :)
