### ISSUE TITLE
DotEnv class not found

### ISSUE THREAD

**Issue by mvcmaker** [zoonman/linkedin-api-php-client#3]
Hi,
there's no way to execute the index.php file due it fails when load the DotEnv/DorEnv class, due does not exists, and I followed all the documentation.
How is the way to fix this?

**Comment by iamsalnikov** [comment]
@mvcmaker did you run `composer install` from project's root?

**Comment by mvcmaker** [comment]
No, documentation doesn't tell that you need to do that. I've done it just now, from the root rirectory which contains vendor/, src/ examples/ and tests/ folders, the result is the same:
```
d:\wamp\www\drs\lib\linkedin>php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

d:\wamp\www\drs\lib\linkedin>
```
Besides that, I've changed the use of the failing loading class Dotenv by the next chunk of code:

```
// import environment variables from the environment file
/*$dotenv = new Dotenv\Dotenv(dirname(__DIR__));
$dotenv->load();*/
$fileTest = __DIR__ . "/../.env";
$fileTest2 = dirname(__FILE__) . "/../.env";
if(file_exists($fileTest)) {
    $dotenvLines = file($fileTest);

}
else
    throw new Exception("File .env not found in {$fileTest}");

foreach($dotenvLines as $dotenv) {
    putenv($dotenv);
}

echo "Loaded successfully lines:";
var_dump(getenv('LINKEDIN_CLIENT_ID'));
var_dump(getenv('LINKEDIN_CLIENT_SECRET'));
```
The result is now that the code executes fine but when I try to load the redirectUrl, the result is that

> The passed in client_id is invalid "<hidden>"
So there's something else that fails.

**Comment by mvcmaker** [comment]
Hi,
there was an error while maging the putenv() calls. Due the call to file() function doesn't include the skip new lines, the return carriage data was appended to the end of the client id and passed as the result url calling, so was an erroneus client id.
The working code now results as here:

```
foreach($dotenvLines as $dotenv) {
    putenv($dotenv);
}

echo "Loaded successfully lines:";
var_dump(getenv('LINKEDIN_CLIENT_ID'));
var_dump(getenv('LINKEDIN_CLIENT_SECRET'));

// we need a session to keep intermediate results
// you can use your own session persistence management
// client doesn't depend on it
session_start();

// instantiate the Linkedin client
$client = new Client(
    getenv('LINKEDIN_CLIENT_ID'),
    getenv('LINKEDIN_CLIENT_SECRET')
);
```
