### ISSUE TITLE
Authorization takes me to page with Bummer, something went wrong.  We're having difficulty connecting error

### ISSUE THREAD

**Issue by sayopaul** [zoonman/linkedin-api-php-client#32]
# authorization URL goes to Bummer, something went wrong , We're having difficulty connecting page .
Hey there . Awesome work here on this library however I run into an issue , when I click on the authorization URL generated by the library , it takes me to a page that says Bummer, something went wrong , We're having difficulty connecting. 

I have done everything as suggested by the docs here https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin/context and ensured that the redirect URL I provided has been authorized from my app's page however I still see this page when I try to authorize . This is what the authorization URL looks like ( I removed client ID for reasons ) . My redirect URL is set to my localhost .

https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=MY_CLIENT_ID&redirect_uri=http%3A%2F%2F127.0.0.1%2Fsocial-post%2Fcallback&state=MY_STATE&scope=r_basicprofile%20r_emailaddress%20w_share

**Comment by zoonman** [comment]
Looks like an error coming from LinkedIn itself.
Try to run your stuff couple hours later.

**Comment by sayopaul** [comment]
Wow , Thanks for the quick response . Alright I would try that . It has been happening for about three hours now , but I would try later and provide feedback . Thank you very much .

**Comment by zoonman** [comment]
You can try the demo with my app https://www.zoonman.com/projects/linkedin-client/demo/ if it works double check your settings and make sure that redirectUrl is set correctly and your code is fine.

**Comment by sayopaul** [comment]
It is strange but it works fine , however when I ran the demo script index.php in the examples folder it gave me the same Bummer error .

**Comment by zoonman** [comment]
You should have something like this in your app settings.

<img width="860" alt="screen shot 2018-12-21 at 17 20 12" src="https://user-images.githubusercontent.com/576297/50365923-cc005680-0544-11e9-8620-755b6d7c8c94.png">

**Comment by zoonman** [comment]
And you should list yourself as developer to on the "Roles" page.

**Comment by zoonman** [comment]
Does it work now?

**Comment by sayopaul** [comment]
Fixed ! It now works . Thank you so much . All I did was ensure that everything matched perfectly . The scopes in the URL and app page had to be the same and also I changed the redirect_uri from 127.0.0.1 to localhost and it works perfectly . Do I close the issue ?

**Comment by zoonman** [comment]
Yes, please. Good luck & Merry Christmas!

**Comment by sayopaul** [comment]
Thank you very much .

Same to you Sir ! 😁
