### ISSUE TITLE
RequestException produced on getAccessToken method

### ISSUE THREAD

**Issue by mvcmaker** [zoonman/linkedin-api-php-client#6]
Hi,
when I try to execute the oauth2 proces (with the examples/index.php page), it throws the next RequestException when I execute as request uri http://localhost:8080:

> ["message":protected]=>
> --
>   | string(134) "cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

This is a fragment of the var_dump of the exception variable, I do not post the whole variable due is very long and contains client_secret keys.
Besides that the code fails, due is passed to responseArray a null object ($ex->getResponse()) that is null and produces a fatal error, I'd like to know why the same code runs fine in a normal server and in local host fails this. Could be the possibility that linkedin endpoint only accepts ssl connections due the documentation don't tell about that?

**Comment by zoonman** [comment]
Your problem is related to the lack of  Certificate Authority (CA) bundle. 
Please, read answer here  https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by mvcmaker** [comment]
I think there's something related with the local server developer configuration. The problem is that the solution this post you give me is only available by xampp server, and I'm using wamp only. I'll try to replicate the steps on wamp, probably it works and I let you know. 
Many thanks @zoonman !

Dani

**Comment by zoonman** [comment]
This problem is not related to WAMP/XAMP. This problem is related to PHP configuration, Curl specifically. https://stackoverflow.com/questions/21114371/php-curl-error-code-60

**Comment by mvcmaker** [comment]
Wow! Accoriding to this post, is very asy to solve, really? You only have to download a valid certificate and link it in php.ini and that's all. Let me to test, @zoonman but until tomorrow morning I will not do it, due I'm working now in my second company, in the UAB, I'll give you my feedback tomorrow. Many thanks again!

**Comment by mvcmaker** [comment]
Hi @zoonman ! 
It worked! By adding simply the curl.cainfo line to my php.ini configuration, that's all to work. The only problem is that when you execute the php command to open the server directly from command line as follows
>php -S localhost:8080 -t examples
then the php.ini loaded not is the same that points the wamp apache, is other there are in wamp/bin/php/php7.1.8 and the best practice is to update everywhere you find a php.ini in your system.
Thanks a lot, you're very good by helping me in very little time!

**Comment by zoonman** [comment]
You can run this command to view the other php.ini

```
php -r "echo php_ini_loaded_file();" 
```
