### ISSUE TITLE
An issue when working linkedin api from CLI php program

### ISSUE THREAD

**Issue by mvcmaker** [zoonman/linkedin-api-php-client#7]
Hi @zoonman ,
My goal is to achieve to work via command line with linkedin api, si my first approach is that I've modified your examples/index.php file to stop the code execution when arrives the code variable. This is the little modification I've done:

```
if (isset($_GET['code'])) { // we are returning back from LinkedIn with the code
    if (isset($_GET['state']) &&  // and state parameter in place
        isset($_SESSION['state']) && // and we have have stored state
        $_GET['state'] === $_SESSION['state'] // and it is our request
    ) {
        //pp($_SERVER);
        if(!isset($_GET['use_code']) || $_GET['use_code'] != 1) {
            $requestUrl = getUrlWithQs();
            echo "<p>Authorization code for one use detected!</p>";
            $finalUrl = $requestUrl . "&use_code=1";
            echo "<p>This is the 1 use code to get the access token:</p>";
            echo "<pre>{$_GET['code']}</pre>";
            echo "<a href='{$finalUrl}'>Click here to complete the request</a>";
        }
        else {
            try {
                // you have to set initially used redirect url to be able
                // to retrieve access token
                $client->setRedirectUrl($_SESSION['redirect_url']);
                // retrieve access token
```

Is just a s imple conditional to stop the use of the exchange token information, as you can see, because my goal is just copy and pcaste this code and use it in my command line program.
The problem is that when I call to getAccessToken method, it throws the next exception:

> Error: Error code 400: Client error: `GET https://www.linkedin.com/oauth/v2/accessToken?grant_type=authorization_code&code=AQRD3anvX6nR9rtwh3TUyuqO9X8C4SFlhm8fXUdNG4nNbRlui7_kikrxcu-TQWC65QIiwbcfLAoE9NP6Vtn27qIH19bHceGaJl2I3mvohsJxCNaEFWPua2xoJi5SCL7o-esAGW95jMp15MJEUL3SXZnjIBYQnw&redirect_uri=https%3A%2F%2Fsrvs2.drsecurityapp.com%2Fappservices%2Flib%2Flinkedin-api-php-client%2Fexamples&client_id=78q2cbpxkl2g0d&client_secret=0cC9ja0rDKqWlaFg` resulted in a `400 Bad Request` response:
> {"error":"invalid_redirect_uri","error_description":"Unable to retrieve access token: appid/redirect uri/code verifier d (truncated...)
> . Description: Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists

Why can happen this, this is because the command line doens't return any requres_uri?
Thanks,

Dani

**Comment by zoonman** [comment]
Yes, in CLI you will not have redirect_uri. There is no flow for CLI implementation whatsoever.
The best approach it is to do a regular OAuth flow and store token to a file or database after you have finished linking.
Next, you will need to load token from file and setup new token.

You need save token at this line https://github.com/zoonman/linkedin-api-php-client/blob/master/examples/index.php#L51 in file  which will go through the linking flow.
```
file_put_contents('token.txt', $accessToken);
```

Later, in your CLI script, you have to load this token from this file and use it like this

```
$client = new Client(
    getenv('LINKEDIN_CLIENT_ID'),
    getenv('LINKEDIN_CLIENT_SECRET')
);
// you are loading token into $tokenString var
$tokenString = file_get_contents('token.txt'); 

// creating AccessToken object
$accessToken = new AccessToken($tokenString);

// setting setAccessToken for linkedin client
$client->setAccessToken($accessToken);

// now you should be able to call API
```

Make sure that you will have correct path to `token.txt` in examples.

**Comment by zoonman** [comment]
Don't forget to include 
```
use LinkedIn\Client;
use LinkedIn\AccessToken;
```

**Comment by mvcmaker** [comment]
Many thanks @zoonman,
My next approach will be now to serlialize the accessToken objet to include it in my custom Linkedin class for work on CLI and using it.
Can I ask you some new questions related on what can be with this access token? My next process will be to refresh with a cron the access token in order to have it all the time not expired and can interact all the time I need with linkedin api. Is there one method that can refresh the access token for a given access token and what should be the way to do it?
Could I ask your contact address or something to can contact you in private to ask particual things on my way to use your linkedin api?
Thanks again,
Dani (from Barcelona, unfortunately we're living on a very bad times these days :'(

**Comment by zoonman** [comment]
You won't be able to refresh token by cron because you have to go through the oauth flow again. 
Token expires in 60 days https://developer.linkedin.com/docs/oauth2

You can signup here https://www.linuxquestions.ru/english
Go to https://www.linuxquestions.ru/users/zoonman and click Ask Privately.
Next fill out details and we can there.

**Comment by mvcmaker** [comment]
Many thanks again @zoonman,
I'll try to disturb you the less as possible.

**Comment by mvcmaker** [comment]
Hi @zoonman,
I use something similar like you but adding an improvement, I've just put the serialized object in the token file with serialize() function, the I've get by calling the unserialize() and then I've just got the object itself and no new AccessToken() call was needed. Just when you set the $client->setAccessToken() with the unserialized object itself, worked perfectly.
Thanks again,
Dani

**Comment by mvcmaker** [comment]
Many thanks again @zoonman,
I'll try to disturb you the less as possible.
