### ISSUE TITLE
$linkedIn->setAccessToken('access_token_from_db');

### ISSUE THREAD

**Issue by said-java** [zoonman/linkedin-api-php-client#9]
$linkedIn->setAccessToken('access_token_from_db');

Fatal error: Uncaught Error: Call to a member function getToken() on string in /home/104455.cloudwaysapps.com/gkbdhdrmcr/public_html/vendor/zoonman/linkedin-api-php-client/src/Client.php:335 Stack trace: #0 /home/104455.cloudwaysapps.com/gkbdhdrmcr/public_html/vendor/zoonman/linkedin-api-php-client/src/Client.php(410): LinkedIn\Client->api('people/

**Comment by iamsalnikov** [comment]
@said-java as I understand, you have to pass to `Client::setAccessToken()` instance of `\LinkedIn\AccessToken`:

```
$linkedIn->setAccessToken(new \LinkedIn\AccessToken('access_token_from_db'))
```

**Comment by said-java** [comment]
@iamsalnikov 
// ... please, add composer autoloader first
include_once __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

// import client class
use LinkedIn\Client;

// instantiate the Linkedin client
$client = new Client(
    'LINKEDIN_APP_CLIENT_ID',  
    'LINKEDIN_APP_CLIENT_SECRET'
);
$acesstoken="xxxxxxxxxxxxxxx";
$client->setAccessToken($acesstoken);
response:

Fatal error: Uncaught Error: Call to a member function getToken() on string in /home/104455.cloudwaysapps.com/gkbdhdrmcr/public_html/vendor/zoonman/linkedin-api-php-client/src/Client.php:335 Stack trace: #0 /home/104455.cloudwaysapps.com/gkbdhdrmcr/public_html/vendor/zoonman/linkedin-api-php-client/src/Client.php(410): LinkedIn\Client->api('people/

**Comment by iamsalnikov** [comment]
@said-java where did you find such way for setting up access token? I did not find same words in documentation.

@zoonman maybe we have to add something like typehinting to `LinkedIn\Client::setAccessToken()` method? And describe in readme how to set up previously saved token?

**Comment by zoonman** [comment]
@iamsalnikov I updated readme. I think, I need to add type handling there. 
I think passing of object is complicated for newbies and I have to instantiate AccessToken object dynamically.

**Comment by zoonman** [comment]
@said-java read [readme](https://github.com/zoonman/linkedin-api-php-client/blob/master/README.md). I have it updated. 
Also, you can update the library. Read Composer's documentation https://getcomposer.org/doc/ if you are not familiar with that.

**Comment by said-java** [comment]
@zoonman im expert in php 

thanks.....
